const MAX_FULL_NAME_LENGTH = 255;
const MIN_FULL_NAME_LENGTH = 3;
const MIN_DESCRIPTION_LENGTH = 10;
const MAX_DESCRIPTION_LENGTH = 255;
const MAX_NUMBER_OF_PHOTOS = 3;

export { 
        MIN_FULL_NAME_LENGTH,
        MAX_FULL_NAME_LENGTH,
        MIN_DESCRIPTION_LENGTH,
        MAX_DESCRIPTION_LENGTH,
        MAX_NUMBER_OF_PHOTOS
};