const DEFAULT_REGISTRATION_STAGE_ORDER_NUMBER = 1;
const MAX_ORDER_COLUMN_NAME = 'maxOrderNumber';
const MIN_ORDER_COLUMN_NAME = 'minOrderNumber';

export {
    DEFAULT_REGISTRATION_STAGE_ORDER_NUMBER,
     MAX_ORDER_COLUMN_NAME,
     MIN_ORDER_COLUMN_NAME
};
