const DEFAULT_REGISTRATION_STAGE_ID = 1;
const MAX_ORDER_COLUMN_NAME = 'max_order_number';
const MIN_ORDER_COLUMN_NAME = 'min_order_number';

export {
     DEFAULT_REGISTRATION_STAGE_ID,
     MAX_ORDER_COLUMN_NAME,
     MIN_ORDER_COLUMN_NAME
};
