const DEFAULT_REGISTRATION_STAGE_ID = 1;
const MAX_ORDER_COLUMN_NAME = 'maxOrderNumber';
const MIN_ORDER_COLUMN_NAME = 'minOrderNumber';

export {
     DEFAULT_REGISTRATION_STAGE_ID,
     MAX_ORDER_COLUMN_NAME,
     MIN_ORDER_COLUMN_NAME
};
